---
title: " "
output: html_notebook
---

### Áreas de oportunidad:


##### Comité Externo de Evaluación.

El CEE duplica un objetivo implícito en el proceso de evaluación del instrumento establecido (SIEVA).

La calidad de los productos está claramente ponderada por el SIEVA, la calidad de los productos está definida acorde con estándares internacionales ej. Indexación en SCIMAGO, Thomson Reuters Master Journal list , JCR, lo cual está en línea también con los requerimientos del Sistema Nacional de Investigadores.
La puntuación asignada por el SIEVA además de considerar todas las actividades que la reglamentación vigente por el EPA establece como obligaciones de los investigadores (ej. Docencia, Investigación, Difusión, vinculación, etc.), ya considera el aspecto de calidad explícito en la clasificación de publicaciones incluidas las revistas, libros y capítulos de libro.  


Si bien se reconoce que el propósito original de dicho órgano es consistente con la búsqueda de calidad y trasparencia, en la práctica puede generar resultados no consistentes. ^[La fuente de información para esta sección del análisis se basa en la matriz del dictamen de la CEE, misma que se  difundió públicamente mediante el Acta de sesión  del CCE en correo con fecha  dia 11 de marzo de 2019] 
  