---
title: " "
output: html_notebook
---
  
### II. Esquema de evaluación de la producción académica como mecanismo de fortalecimiento del compromiso institucional.

Se tienen áreas de oportunidad para mejorar los mecanismos de evaluación. Estos actúan como un esquema de transmisión de señales, que a su vez se traducen en incentivos que dirigen el desempeño de los investigadores.


##### Propuesta I.

La propuesta concreta es incluir una nueva figura denominada:  Compromiso con la Formación de comunidad académica (FCA) mediante un equema de puntuación que valore el compromiso institucional medido a través del indicador FCA que fomente la participación en actividades de docencia en la institución en los siguientes rangos:
  
a) Compromiso con la Formación de comunidad académica entre 100-149hrs 10 pts.

b) Compromiso con la Formación de comunidad académica entre 150-179 hrs 15 pts.

c) Compromiso con la Formación de comunidad académica >=180hrs. 20 pts.2

Los rangos están pensados con base en la distribución histórica de participación de docencia ya que como se analizó en la sección anterior, se sabe que la participación promedio de un investigador en horas clase por periodo a evaluar es de 88 y 85 hrs para Mujeres y hombres respectivamente.

Por lo tanto, se propone asignar un puntaje para la nueva figura (Formación de comunidad académica (FCA), cuando el investigador muestre su compromiso al impartir entre 100 y 149 hrs en el periodo. Esta es la primera categoría.
                                                                  
Una segunda categoría con 15 pts. cuando el investigador imparta entre 150 y 179hrs. Y el puntaje máximo de 20 cuando el investigador participe con 180 horas o más (el equivalente a un curso de 45 hrs. por semestre en el periodo a evaluar).
                                                                  
Como ya se discutió en la sección anterior, fortalecer las actividades docentes de la institución representa una prioridad, como se mostró actualmente existen sedes que promedian 39 hrs. en el periodo evaluado, lo que representa un promedio de 20 horas por año, en un claro ejemplo de área de oportunidad.
                                                                  
                                                                  
##### Propuesta II
     
La creación del Diplomado: **Análisis de los Patrones de salud en las fronteras  PSF.**     



Hoy en día existe una creciente demanda entre la comunidad para cursar programas que generen habilidades con base en conocimientos especializados. El Colegio de la Frontera Norte es una institución líder en el ecosistema de centros públicos de CONACyT con una vocación temática que es reconocida como su principal fortaleza y un referente entre las instituciones académicas del país: el estudio de las fronteras desde una perspectiva integral.
                                                                  
                                                                  
En este contexto el abordaje de las condiciones de salud que se presentan en la regiones fronterizas constituyen un campo de estudio de enorme potencial en el que El Colef puede aportar al dar respuesta a la demanda por contenidos de alta especialidad existente. Y al mismo tiempo aprovechar el capital humano especializado que se ha conformado en esta área del conocimiento  en El Colef.


##### Características del programa:

El Diplomado en **Análisis de los Patrones de salud en las fronteras**  PSF es un programa único que combina una sólida base teórica desde  una orientación a nuevas metodologías de análisis en el contexto  de grandes volúmenes de datos.
En especial se sustenta en el enfoque de análisis bajo preceptos de replicabilidad, utilizando herramientas que hoy marcan el rumbo para el análisis de datos como R markdown y Python.

La creación de este progama permitirá atraer recursos, necesarios en la coyuntura actual que enfrentan los CPI en el país ya que es un programa auto susntencable en terminos finencieros.


