---
title: ""
output: html_notebook
---




#### Hacia la construcción de una estrategia para fortalecer el compromiso institucional: Insumos para la toma de decisiones.

---

El presente ejercicio busca aportar elementos y servir de insumo para analizar los indicadores de producción de los investigadores en la institución con base en la información disponible para la evaluación de SIEVA 2018.

Se enfatizan las áreas de oportunidad detectadas para trabajar en la construcción de estrategias que permitan fortalecer el compromiso institucional y medir su impacto.


Parte del reconocimiento de que el análisis de la información histórica sobre el desempeño de cada investigador representa un insumo muy valioso para detectar las debilidades en el compromiso institucional entre los investigadores de la institución.

Concretamente los patrones observados mediante el instrumento de evaluación SIEVA representan un expresión directa y objetiva del compromiso institucional que cada individuo está aportando a la institución.

Un diagnóstico claro basado en instrumentos de evaluación objetivos permitiría tomar decisiones pertinentes que ayuden al diseño de una estrategia de compromiso institucional efectiva.

Con base en al areas de oportnidad detectadas por el  análisis se detallan **dos propuestas concretas** para el diseño de estrategias para reforzar el compromiso institucional de los investigadores en este rubro.
